"""celery_init

Revision ID: 068ed6276515
Revises: 4757bd3f8439
Create Date: 2026-05-15 09:39:18.784643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068ed6276515'
down_revision: Union[str, Sequence[str], None] = '4757bd3f8439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_terms', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('academic_terms', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('academic_terms', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('buildings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('buildings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('buildings', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('course_catalog', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('course_catalog', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('course_catalog', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('course_offerings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('course_offerings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('course_offerings', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('degree_programs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('degree_programs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('degree_programs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('departments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('departments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('employee_experience', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('employee_experience', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('employee_experience', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('employees', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('employees', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('enrollments', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('enrollments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('enrollments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('program_requirements', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('program_requirements', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('program_requirements', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('research_labs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('research_labs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('research_labs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('rooms', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('schools', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('schools', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('schools', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('student_programs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('student_programs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('student_programs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('students', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'deleted_at')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    op.drop_column('student_programs', 'deleted_at')
    op.drop_column('student_programs', 'updated_at')
    op.drop_column('student_programs', 'created_at')
    op.drop_column('schools', 'deleted_at')
    op.drop_column('schools', 'updated_at')
    op.drop_column('schools', 'created_at')
    op.drop_column('rooms', 'deleted_at')
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'created_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('research_labs', 'deleted_at')
    op.drop_column('research_labs', 'updated_at')
    op.drop_column('research_labs', 'created_at')
    op.drop_column('program_requirements', 'deleted_at')
    op.drop_column('program_requirements', 'updated_at')
    op.drop_column('program_requirements', 'created_at')
    op.drop_column('enrollments', 'deleted_at')
    op.drop_column('enrollments', 'updated_at')
    op.drop_column('enrollments', 'created_at')
    op.drop_column('employees', 'deleted_at')
    op.drop_column('employees', 'updated_at')
    op.drop_column('employees', 'created_at')
    op.drop_column('employee_experience', 'deleted_at')
    op.drop_column('employee_experience', 'updated_at')
    op.drop_column('employee_experience', 'created_at')
    op.drop_column('departments', 'deleted_at')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
    op.drop_column('degree_programs', 'deleted_at')
    op.drop_column('degree_programs', 'updated_at')
    op.drop_column('degree_programs', 'created_at')
    op.drop_column('course_offerings', 'deleted_at')
    op.drop_column('course_offerings', 'updated_at')
    op.drop_column('course_offerings', 'created_at')
    op.drop_column('course_catalog', 'deleted_at')
    op.drop_column('course_catalog', 'updated_at')
    op.drop_column('course_catalog', 'created_at')
    op.drop_column('buildings', 'deleted_at')
    op.drop_column('buildings', 'updated_at')
    op.drop_column('buildings', 'created_at')
    op.drop_column('academic_terms', 'deleted_at')
    op.drop_column('academic_terms', 'updated_at')
    op.drop_column('academic_terms', 'created_at')
    # ### end Alembic commands ###
