"""add_is_active_to_permissions

Revision ID: 81cc6a6859b2
Revises: 616189fe706c
Create Date: 2026-06-01 10:40:13.938297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81cc6a6859b2'
down_revision: Union[str, Sequence[str], None] = '616189fe706c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'is_active')
    # ### end Alembic commands ###
